package models

type RegistrationRequest struct {
	Id        string            `json:"id"`
	Name      string            `json:"name"`
	K8s       bool              `json:"k8s"` //indication if the agent is in a K8s Pod
	Ip        string            `json:"ip"`
	SbiPort   int               `json:"sbiport"`
	AgentPort int               `json:"agentport"`
	Labels    map[string]string `json:"labels"`
}
type RegistrationResponse struct {
	Id string `json:"id"` //endpoint identity generated by the controller
}

type SubscribeRequest struct {
	Id       string        `json:"id"` //endpoint identity
	Services []ServiceName `json:"services"`
}

type SubscribeResponse struct {
	Endpoints map[string]Endpoint     //list of relevant endpoints
	Services  map[ServiceName]Service //list of subscibed services
}

type EndpointUpdates struct {
	Left []string   //identities of left endpoints
	Join []Endpoint //list of joined endpoints
}

type EndpointUpdatesConfirm struct {
	Ok bool
}
