package n43

import (
	"etrib5gc/sbi/models"
	"net"
)

type UpfPathQuery struct {
	Dnn    string
	Snssai models.Snssai
	Nets   []string
}

//represent a path consisting of Nodes in user plane from access network to
//data network

type UpfPath struct {
	Path []*PathNode //UPF nodes in the path
	Ip   net.IP      //Ue's IP generated by UPMF
}

type PathNode struct {
	Id       string //Upf Identity (read from its configuration)
	UlIp     net.IP //ip of the uplink face
	DlIp     net.IP //ip of the downlink face
	PfcpIp   net.IP //UPF's IP
	PfcpPort int    //UPF's port for PFCP
}

//data model function gettopo for upmf2fe:
type UpfNode struct{
	Id			string						// Upf Identity
	Slices  	[]models.Snssai	
	SbiIp		net.IP						// UPF's IP
	SbiPort		int							// UPF's port for Sbi
	Infs 		map[string][]NetInf			// Data Infs for Upf
}

type TopoUpf struct{
	SlicesTopo		map[string]models.Snssai
	Nets        	map[string]uint8
	Nodes       	map[string]*UpfNode	
}

type NetInf struct{
	Id 			string
	Netname		string
	Nettype     uint8
	Addr		net.IP
}
